# Generated by Django 5.0.6 on 2024-05-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
